### ISSUE TITLE
'net6.0-android' is out of support

### ISSUE THREAD

**Issue by vovanb** [exendahal/MAUI_Notification#1]
I downloaded your project, but can not compile it because outdate .net 6
`
Error	NETSDK1202	The workload 'net6.0-android' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.	MAUI_Notification	C:\Program Files\dotnet\sdk\8.0.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets	38	`	

any chance you can upgrade project to .net 8?

**Comment by exendahal** [comment]
Updated to .NET 8. Resolves #1
